version: '3'

services:
  client:
    build: ./client/
    volumes:
      - ./client:/client:rw
      - client_node_modules:/client/node_modules
  # server:
  #   build: ./server/
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./server:/server:rw
  #     - server_node_modules:/server/node_modules
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html:ro
      - client_node_modules:/usr/share/nginx/html/node_modules:ro

volumes:
  client_node_modules:
  # server_node_modules:
